---
title: "Burdened Populations, Cost-Benefit, and GoFundMe"
author: "Corban Nemeth"
date: "5/21/2019"
output: 
  tufte::tufte_html: default
---

Benefit-cost analysis seeks to quantify the impacts of policy decisions in economic terms. Comprehensive benefit-cost analysis requires econometric and statistical analysis that, if taken in isolation, can overshadow the normative underpinnings of policy decisions. In the State of Washington, the Washington State Institute for Public Policy conducts benefit-cost analysis for legislative decision makers to aid in policy formulation and deployment. WSIPP uses meta-analysis to derive their expected benefit ratios for a wide variety of policy proposals (WSIPP, 2018). Meta-analysis is a statistical technique to isolate effect sizes from a variety of studies and distill it into a generalized impact. In WSIPP’s case, this impact is regional to the State of Washington. This review critically analyzes “Interventions to reduce unnecessary emergency department (ED) visits: General education on appropriate ED use,” a WSIPP benefit-cost analysis. By considering target populations, specific costs and benefits, distributional concerns, and sensitivity analysis, this review demonstrates that while a multitude of costs, benefits, and contingencies are taken into effect, specific moral arguments regarding target populations should not be abstracted out of the equation by decisionmakers overwhelmed with robust quantitative analysis.

The single study in the WSIPP meta-analysis was ultimately inconclusive on its own merits. The study “evaluated the dissemination of a booklet to all members of a health insurance plan who received Medicaid benefits” explaining the appropriate use of emergency department services and treatments for common conditions (Rector & Venus, 1999). The WSIPP analysis considers costs of booklets for every Medicare household in Washington to taxpayers, as well as the savings associated with reduced ED usage on the state’s economy as a whole (WSIPP, 2014). What isn’t considered is the opportunity cost of a Medicaid eligible patient not going to the emergency room when it could be potentially-life saving. 
	
By nudging the Medicaid population to not take advantage of emergency room services, this program may actually impose costs on the low-income population. Given the relatively low income-replacement opportunity cost of the Medicaid population, subsidized insurance benefits, and the high value of a statistical life, it may be rational for Medicaid eligible patients to err on the side of emergency room visits, thereby burdening the Medicaid system, hospitals, and taxpayers ^[To provide a simplistic example of this quandary, consider the following scenario: The hourly wage-earning opportunity cost of a low-income head-of-household for a family of four earning 200% of the Federal Poverty Limit is \$24.66 an hour, based on a \$51,500 annual salary. If we assume the individual gives up four hours of earning potential to utilize emergency room services, the opportunity cost to the individual is about \$100, plus a ballpark \$250 copay and deductible. A study estimates that the proportion of ER visits that end in death is .77 in 1000, or 0.077% (Probst, 2016). Given a modal value of a statistical life of \$7 million (WSIPP, 2018), the expected cost of death for a given ER visit is $5,390 (0.077% x 7 million), greatly exceeding the patient cost for the visit.]. For an individual on Medicaid, the simplistic comparison of opportunity cost with a probabilistic expected cost of death is heavily weighted towards utilizing ED services to prevent the off-chance of a catastrophic outcome. However, these costs are not captured by the WSIPP analysis.

The plausible rationality of ED usage by Medicaid patients presents an interesting moral dilemma that exceeds the scope of WSIPP and this benefit-cost analysis but is critical for decisionmakers to consider. Decisionmakers must consider whether the burden of ED cost prevention and utilization falls to the Medicaid eligible population through nudging them towards non-utilization based on a booklet suggesting ED use be limited to extraordinary circumstances. I would suggest that decision-makers consider, as the root study in the meta-analysis also suggests (Rector & Venus, 1999), decisionmakers look to a systematic health care approach involving the managed care organization as a whole.

The normative decision discussed above relies on the value of a statistical life (VSL). WSIPP calculates the VSL based on the human capital approach, which calculates the present value of career earnings, and also the value of a statistical life approach, which calculates “the total monetary value that people place on reduced risks of death, or the amounts that they are willing to accept for increased levels of mortality risk” (WSIPP, 2018). However, the value of a statistical life does not necessarily represent the value of a societal life ^[To be known also as the “GoFundMe Index,” based on frequent and misleading comparisons between charity contributions and the taxation costs socialized medicine present on social media.]. If one takes the modal VSL estimate of $7 million and divides it by the total population of Washington State, it works out to 93 cents per capita. Perhaps optimistically, I would expect the amount a given taxpayer would contribute to directly save a life would be greater than 93 cents. For cases where whole populations are contributing to life-savings effort, the value of a societal life could represent a more accurate social cost to potential deaths.
	
Monte Carlo simulations are used to conduct sensitivity analysis. The results of the Monte Carlo simulation inform the “chance the program will produce benefits greater than the cost” metric, which in this case is 49% (WSIPP 2014). In other words, there is a 49% probability that the expected benefit-cost ratio does not materialize.

WSIPP does not assign recommendations to their benefit-cost policies. Instead, they document the benefit-cost ratio and probabilistic sensitivity analysis and allow stakeholders and decision makers to draw their own conclusions. With this in mind, I would urge policymakers to consider who is being burdened by their policies in addition to potential expected savings in order to address systemic causes of high health costs rather than effects. ED usage is expensive, but Medicaid patients are uniquely vulnerable to societal pressures that this analysis does not take into account.
